### ISSUE TITLE
link no longer exists

### ISSUE THREAD

**Issue by Thegreatesthumphrey** [learn-co-curriculum/dsc-significance-p-value#1]
the second link "regression continued' no longer exists

**Comment by hoffm386** [comment]
Thanks for flagging! Looks like a certificate issue on their end, with intermittent issues. I went ahead and replaced the link with an archived link that should be more stable https://github.com/learn-co-curriculum/dsc-significance-p-value/commit/2f883aa17ed794c6e763eb669f4e60922bd5c717
